local lz = require("lz.n")
local keymap = lz.keymap("nvim-tree.lua")

keymap.set("n", "<A-1>", function()
	vim.cmd.BufferGoto(1)
end)
keymap.set("n", "<A-2>", function()
	vim.cmd.BufferGoto(2)
end)
keymap.set("n", "<A-3>", function()
	vim.cmd.BufferGoto(3)
end)
keymap.set("n", "<A-4>", function()
	vim.cmd.BufferGoto(4)
end)
keymap.set("n", "<A-5>", function()
	vim.cmd.BufferGoto(5)
end)
keymap.set("n", "<A-6>", function()
	vim.cmd.BufferGoto(6)
end)
keymap.set("n", "<A-7>", function()
	vim.cmd.BufferGoto(7)
end)
keymap.set("n", "<A-8>", function()
	vim.cmd.BufferGoto(8)
end)
keymap.set("n", "<A-9>", function()
	vim.cmd.BufferGoto(9)
end)
keymap.set("n", "<A-w>", function()
	vim.cmd.BufferClose()
end)
