local lz = require("lz.n")
local keymap = lz.keymap("smart-splits.nvim:")

keymap.set("n", "<A-h>", require("smart-splits").resize_left)
keymap.set("n", "<A-j>", require("smart-splits").resize_down)
keymap.set("n", "<A-k>", require("smart-splits").resize_up)
keymap.set("n", "<A-l>", require("smart-splits").resize_right)
keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left)
keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down)
keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up)
keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right)
keymap.set("n", "<C-\\>", require("smart-splits").move_cursor_previous)
keymap.set("n", "<leader><leader>h", require("smart-splits").swap_buf_left)
keymap.set("n", "<leader><leader>j", require("smart-splits").swap_buf_down)
keymap.set("n", "<leader><leader>k", require("smart-splits").swap_buf_up)
keymap.set("n", "<leader><leader>l", require("smart-splits").swap_buf_right)
